// <auto-generated />
using System;
using CustomerProfile.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomerProfile.Migrations
{
    [DbContext(typeof(UserProfileDbContext))]
    [Migration("20251226190254_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerProfile.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddressType")
                        .HasColumnType("integer");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocalGovernmentArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("VerificationMethod")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationReference")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("CustomerProfile.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountTier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AlternateEmail")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("AlternatePhoneNumber")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<DateTimeOffset?>("BVNAddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BvnBase64Image")
                        .HasColumnType("text");

                    b.Property<string>("BvnHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.PrimitiveCollection<float[]>("FaceEncodings")
                        .HasColumnType("real[]");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPoliticallyExposedPerson")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWatchlisted")
                        .HasColumnType("boolean");

                    b.Property<string>("KYCStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("LastAMLScreening")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastTransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaidenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("NINAddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NinBase64Image")
                        .HasColumnType("text");

                    b.Property<string>("NinHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.PrimitiveCollection<int[]>("NotificationChannels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("PoliticallyExposedPersonSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StateOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAccountNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset?>("WatchlistScreenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WatchlistScreenedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("CustomerProfile.Entities.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanSetProfile")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserPhoneNumber");

                    b.ToTable("VerificationCodes", (string)null);
                });

            modelBuilder.Entity("CustomerProfile.Entities.Address", b =>
                {
                    b.HasOne("CustomerProfile.Entities.UserProfile", "UserProfile")
                        .WithMany("Addresses")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CustomerProfile.Entities.UserProfile", b =>
                {
                    b.OwnsMany("CustomerProfile.Entities.KYCDocument", "KycDocuments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text");

                            b1.Property<string>("DocumentMimeType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DocumentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTimeOffset?>("ExpiryDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("FileUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean");

                            b1.Property<DateTimeOffset?>("IssuedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("VerificationReference")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("VerifiedBy")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("KYCDocuments", (string)null);

                            b1.WithOwner("Customer")
                                .HasForeignKey("CustomerId");

                            b1.Navigation("Customer");
                        });

                    b.OwnsMany("CustomerProfile.Entities.NextOfKin", "NextOfKins", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AlternatePhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("CanContactInEmergency")
                                .HasColumnType("boolean");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Occupation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("NextOfKins", (string)null);

                            b1.WithOwner("Customer")
                                .HasForeignKey("CustomerId");

                            b1.Navigation("Customer");
                        });

                    b.OwnsMany("CustomerProfile.Entities.RiskAssessment", "RiskAssessments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AssessmentDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Assessor")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("RiskAssessmentSummary")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("RiskAssessmentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("RiskLevel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("RiskAssessments", (string)null);

                            b1.WithOwner("Customer")
                                .HasForeignKey("CustomerId");

                            b1.Navigation("Customer");
                        });

                    b.OwnsOne("CustomerProfile.Entities.ValueObjects.NinData", "NinData", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Birthdate")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("EmploymentStatus")
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .HasColumnType("text");

                            b1.Property<string>("Gender")
                                .HasColumnType("text");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<string>("MaritalStatus")
                                .HasColumnType("text");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("text");

                            b1.Property<string>("Nin")
                                .HasColumnType("text");

                            b1.Property<string>("Photo")
                                .HasColumnType("text");

                            b1.Property<string>("Profession")
                                .HasColumnType("text");

                            b1.Property<string>("Religion")
                                .HasColumnType("text");

                            b1.Property<string>("ResidenceAddressLine1")
                                .HasColumnType("text");

                            b1.Property<string>("ResidenceLga")
                                .HasColumnType("text");

                            b1.Property<string>("ResidenceState")
                                .HasColumnType("text");

                            b1.Property<string>("ResidenceStatus")
                                .HasColumnType("text");

                            b1.Property<string>("ResidenceTown")
                                .HasColumnType("text");

                            b1.Property<string>("Signature")
                                .HasColumnType("text");

                            b1.Property<string>("Surname")
                                .HasColumnType("text");

                            b1.Property<string>("TelephoneNo")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.Property<string>("TrackingId")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId")
                                .IsUnique();

                            b1.HasIndex("Id")
                                .IsUnique();

                            b1.ToTable("NinData", (string)null);

                            b1.WithOwner("Customer")
                                .HasForeignKey("CustomerId");

                            b1.Navigation("Customer");
                        });

                    b.OwnsMany("CustomerProfile.Entities.ComplianceCheck", "ComplianceChecks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("CheckType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTimeOffset>("CheckedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CheckedBy")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text");

                            b1.Property<string>("Details")
                                .HasColumnType("text");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<DateTimeOffset?>("NextCheckDue")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("VerificationReference")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("UserProfileId");

                            b1.ToTable("ComplianceChecks", (string)null);

                            b1.WithOwner("UserProfile")
                                .HasForeignKey("UserProfileId");

                            b1.Navigation("UserProfile");
                        });

                    b.OwnsOne("CustomerProfile.Entities.ValueObjects.BvnData", "BvnData", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("BVN")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Base64Image")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateOnly?>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("EnrollmentBank")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("EnrollmentBranch")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LevelOfAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LgaOfOrigin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LgaOfResidence")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MaritalStatus")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("NameOnCard")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber2")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateOnly?>("RegistrationDate")
                                .HasColumnType("date");

                            b1.Property<string>("ResidentialAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StateOfOrigin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StateOfResidence")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("WatchListed")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("Id")
                                .IsUnique();

                            b1.HasIndex("UserProfileId")
                                .IsUnique();

                            b1.ToTable("BvnData", (string)null);

                            b1.WithOwner("UserProfile")
                                .HasForeignKey("UserProfileId");

                            b1.Navigation("UserProfile");
                        });

                    b.Navigation("BvnData");

                    b.Navigation("ComplianceChecks");

                    b.Navigation("KycDocuments");

                    b.Navigation("NextOfKins");

                    b.Navigation("NinData");

                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("CustomerProfile.Entities.UserProfile", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
